spring.application.name = vacation-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/vacation_db
spring.datasource.username = postgres
spring.datasource.password = admin

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

springdoc.swagger-ui.path = /swagger-ui.html